### ISSUE TITLE
Error creating new project

### ISSUE THREAD

**Issue by 012e** [livebud/bud#46]
I followed the instruction to install bud, and `bud create app` doesn't work

![bud](https://user-images.githubusercontent.com/98327371/168474836-c4b3221e-7236-46e1-b235-91722779dab9.gif)

- **OS**: Arch linux
- **go**: version 1.18.2
- **node**: v14.19.2

**Comment by syke99** [comment]
This is due to trying to move files across [partitions](https://github.com/wercker/mhook/issues/12#issuecomment-95364232). /tmp/bud-create-<int> Seems to not exist in whichever partition bud is expecting it to be. I’ve not looked at the source code, so not sure what functionality is needed/should be changed. But this should give someone who’s more familiar a good jumping off point

**Comment by matthewmueller** [comment]
Thanks for opening this issue and trying out Bud @012e! 

As @syke99 mentioned, this is a known issue with partitions. We're already tracking it in https://github.com/livebud/bud/issues/30, where I've written the planned next steps. 

I'm going to close this issue as a duplicate of https://github.com/livebud/bud/issues/30

**Comment by 012e** [comment]
This is weird, I didn't put my /tmp in a different partition.

But I do have other un-formatted OS partitions with /tmp folder inside of it.

What `bud create` did to my /tmp folder: 
![image](https://user-images.githubusercontent.com/98327371/168479130-61636bf0-9769-4820-9dd2-53af86c4d9a6.png)

![image](https://user-images.githubusercontent.com/98327371/168479171-6fcea2b7-2a8d-49a8-9268-b8b3cc71e3c6.png)

**Comment by matthewmueller** [comment]
Hmm, okay. It might be something different then, re-opening. 

If you could try narrowing this down in the codebase, that'd be much appreciated. The create logic is in [this package](https://github.com/livebud/bud/blob/main/internal/command/create/create.go) and I created a [Contributing Guide](https://github.com/livebud/bud/blob/main/Contributing.md) today to help people get Bud installed locally.

Otherwise I'm still going to go with the plan in this comment and we'll try again once that's ready: https://github.com/livebud/bud/issues/30#issuecomment-1126880064

**Comment by 012e** [comment]
@matthewmueller I have just done a setup and tried to `go run main.go -C create app`
What happened: 
![image](https://user-images.githubusercontent.com/98327371/168480487-a168e81d-80db-4910-8c5c-8a5cd9445762.png)

**Comment by matthewmueller** [comment]
Sweet! From your error it looks like the problem is coming from this code block: https://github.com/livebud/bud/blob/7bcf01d370b93878e22c945a84ca29d8eb7bf9f1/internal/command/create/create.go#L55-L70

Can you confirm?

**Comment by matthewmueller** [comment]
@012e would you mind pulling down the branch in this PR and testing if this fixes your problem? https://github.com/livebud/bud/pull/50

**Comment by matthewmueller** [comment]
@012e Would you mind pulling down the branch in the following PR and testing if this fixes your problem? https://github.com/livebud/bud/pull/50

**Comment by 012e** [comment]
Still not working, but `bud create app` created an unfinished project like the previous /tmp/bud-create-<num>, probably something is wrong with npm's permissions
![image](https://user-images.githubusercontent.com/98327371/168523129-a8bd512e-4290-4785-b514-b3141333e773.png)

Do you need the log @matthewmueller?

**Comment by matthewmueller** [comment]
@012e Ah, this is a different error and actually only a problem in the development build, not the production build. 

From within the unfinished project directory, please try running the following:

```sh
npm link livebud $DIR_WHERE_YOU_GIT_CLONED_BUD/livebud
```

This should fail in the same way. I guess because of lack of npm permissions. I guess you could fix this with `sudo npm`.

**Comment by 012e** [comment]
Working perfectly @matthewmueller! BTW,  my default website zoom is 120% and something is off with the css. Was it supposed to look like this?
![image](https://user-images.githubusercontent.com/98327371/168525850-0c59a942-b80d-43f5-8b87-4110db64f248.png)

Closing the issue!

**Comment by 012e** [comment]
Working perfectly @matthewmueller! BTW, my default website zoom is 120%, and the cards are covering the footer
![image](https://user-images.githubusercontent.com/98327371/168526309-f7087c45-a601-413e-a948-1f59b52b12fc.png)

Closing this issue!

**Comment by matthewmueller** [comment]
@012e happy to hear! Did the `sudo npm` work for you? 

Also created an issue on the welcome page: https://github.com/livebud/welcome/issues/1

**Comment by 012e** [comment]
> @012e happy to hear! Did the `sudo npm` work for you?
> 
> Also created an issue on the welcome page: [livebud/welcome#1](https://github.com/livebud/welcome/issues/1)

That's how I fixed the problem
