### ISSUE TITLE
Weird behavior while logging blank exports (Svelte)

### ISSUE THREAD

**Issue by 012e** [livebud/bud#87]
## Reproduce

1. Create a project normally
2. Create any route

```bash
bud new controller hello:/ index show
```

3. `bud run`
4. Add `console.log(hellos);` in the script tag (index.svelte)
5. Go to http://127.0.0.1:3000/ and we will see an error message. For the first time:

```
gob: bad data: field numbers out of bounds
```

- Reload. For the second time:

![image](https://user-images.githubusercontent.com/98327371/170062399-757053e4-4c85-462e-a020-a76d26540451.png)

- What the terminal looks like:

![image](https://user-images.githubusercontent.com/98327371/170064445-ecc4a4f0-a42a-4b79-b9b8-f7e8a2599c32.png)

- More details: 
  - The error message varies between reloads
  - Remove `console.log(hellos);` doesn't fix the problem unless I `bud run` again
 
- OS: Arch linux
- Go: v1.18.2
- Node: v14.19.3
- bud: 0.1.4

**Edit:** app made with `bud build` works normally.

**Comment by matthewmueller** [comment]
Thanks for reporting @012e! I haven't confirmed but I can see how this could be an issue. Can you quickly test if this occurs on an app generated with `bud build`?

```sh
bud build
./bud/app
open http://localhost:3000
```

I'm going to assume that the above works as expected.

I believe the problem is two-fold:

1. [console.log to stdout support](https://github.com/livebud/bud/blob/5a654b700d694dc886b4f6f113e8e33b0dd88f34/package/js/v8/v8.go#L40-L47) was added to the V8 package. This is mighty convenient for debugging. You can test this with:
   ```sh
   echo "console.log('hi')" | bud tool v8
   ```

2. The [v8client](https://github.com/livebud/bud/blob/5a654b700d694dc886b4f6f113e8e33b0dd88f34/package/js/v8client/client.go#L20) is used to avoid needing to recompile V8 for every change to a Go file. What this does is from your development app it will call the `bud tool v8 client` to evaluate JS using the V8 pre-built into Bud. This operates over stdio through a [bare-bones protocol](https://github.com/livebud/bud/blob/v0.1.4/package/js/v8client/protocol.go).

The problem seems to be that the console logs getting logged to stdout are interfering with the data sent over the protocol.

I'm currently reworking the V8 client to not need to know where the `bud` binary is, so I'll work on fixing this in that push.

**Comment by ldlac** [comment]
Not sure if it's related but `localStorage`, `window`, `document` or `setInterval`, etc have a weird behavior too.

```
view: render error ReferenceError: setInterval is not defined
```

when wrapped inside a `if (typeof document != "undefined")` or anything that v8 will appreciate, everything is fine, `console.log` included

**Comment by matthewmueller** [comment]
Hey @ldlac, I just moved this comment into a separate issue. Please have a look at my response there! I'm going to hide your comment since I'd like us to chat about it in that issue!
